version: '3.8'  # Aturan versi yang lebih baru
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: 5Dg$p3L!fT2#xQz
      MYSQL_ROOT_PASSWORD: root_password

  wordpress:
    image: wordpress:latest
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: 5Dg$p3L!fT2#xQz
      WORDPRESS_DB_NAME: wordpress
    ports:
      - "80:80"

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"  # Ganti dengan port lain jika diperlukan
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - wordpress

volumes:
  db_data:
  wordpress_data:
